export const GET_SEND_WARD = 'GET_SEND_WARD';
export const GET_SEND_WARD_SUCCESS = 'GET_SEND_WARD_SUCCESS';
export const GET_SEND_WARD_FAILED = 'GET_SEND_WARD_FAILED';
export const RESET_GET_SEND_WARD = 'RESET_GET_SEND_WARD';
