export const GET_SEND_PROVINCE = 'GET_SEND_PROVINCE';
export const GET_SEND_PROVINCE_SUCCESS = 'GET_SEND_PROVINCE_SUCCESS';
export const GET_SEND_PROVINCE_FAILED = 'GET_SEND_PROVINCE_FAILED';
export const RESET_GET_SEND_PROVINCE = 'RESET_GET_SEND_PROVINCE';
