export const GET_SEND_DISTRICT = 'GET_SEND_DISTRICT';
export const GET_SEND_DISTRICT_SUCCESS = 'GET_SEND_DISTRICT_SUCCESS';
export const GET_SEND_DISTRICT_FAILED = 'GET_SEND_DISTRICT_FAILED';
export const RESET_GET_SEND_DISTRICT = 'RESET_GET_SEND_DISTRICT';
