export const GET_SERVICE = 'GET_SERVICE';
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS';
export const GET_SERVICE_FAILED = 'GET_SERVICE_FAILED';
export const RESET_GET_SERVICE = 'RESET_GET_SERVICE';
